import { SERVICES } from "../content/services.js";
import { INDUSTRIES } from "../content/industries.js";
import { SITE } from "../content/site.js";
import { ROUTES } from "./routes.js";
const staticRoutes = [ROUTES.home, ROUTES.about, ROUTES.compliance, ROUTES.services, ROUTES.industries, ROUTES.clients, ROUTES.gallery, ROUTES.faqs, ROUTES.contact];
const normalizedSiteUrl = (siteUrl: string) => siteUrl.replace(/\/$/, "");
export function getIndexableRoutes(): string[] { return [...staticRoutes, ...SERVICES.map((service) => service.seo.canonicalPath)]; }
export function generateSitemapXml(siteUrl: string): string { const baseUrl = normalizedSiteUrl(siteUrl); return `<?xml version="1.0" encoding="UTF-8"?>\n<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">\n${getIndexableRoutes().map((route) => `  <url><loc>${baseUrl}${route}</loc></url>`).join("\n")}\n</urlset>\n`; }
export function generateRobotsTxt(siteUrl: string): string { return `User-agent: *\nAllow: /\n\nUser-agent: GPTBot\nAllow: /\n\nUser-agent: ChatGPT-User\nAllow: /\n\nUser-agent: ClaudeBot\nAllow: /\n\nUser-agent: PerplexityBot\nAllow: /\n\nUser-agent: Google-Extended\nAllow: /\n\nSitemap: ${normalizedSiteUrl(siteUrl)}/sitemap.xml\n`; }
export function generateLlmsTxt(): string { const services = SERVICES.map((service) => `- [${service.name}](${service.seo.canonicalPath}): ${service.shortTagline}`).join("\n"); const industries = INDUSTRIES.map((industry) => industry.name).join(", "); return `# ${SITE.shortName} — ${SITE.name}\n\n> Private security and manpower services company based in Bengaluru, India. Established ${SITE.established}. ${SITE.yearsInBusiness}+ years, ${SITE.guardsCount}+ guards, ${SITE.clientsCount}+ clients. Serves ${SITE.primaryServiceArea} primarily and ${SITE.secondaryServiceArea.toLowerCase()}.\n\n## Services\n${services}\n\n## Company\n- [About](${ROUTES.about}): company history, service approach, and company information.\n- [Contact](${ROUTES.contact}): enquiry form and available contact details.\n\n## Industries served\n- [Industries](${ROUTES.industries}): ${industries}.\n`; }
